#ifndef MAPVIZ_PLUGINS_PRECISION_PLUGIN_H_
#define MAPVIZ_PLUGINS_PRECISION_PLUGIN_H_

#include <mapviz/mapviz_plugin.h>
#include <mapviz/map_canvas.h>

// C++ standard libraries
#include <string>

// QT libraries
#include <QGLWidget>
#include <QObject>
#include <QWidget>

// ROS libraries
#include <ros/ros.h>
#include <opencv/highgui.h>
#include <cv_bridge/cv_bridge.h>

#include <sensor_msgs/NavSatFix.h>
#include <swri_transform_util/local_xy_util.h>

// QT autogenerated files
#include "ui_precision_config.h"
#include "ui_topic_select.h"

namespace mapviz_plugins
{
  class PrecisionPlugin : public mapviz::MapvizPlugin
  {
    Q_OBJECT

  public:
    enum Anchor {
      TOP_LEFT,
      TOP_CENTER,
      TOP_RIGHT,
      CENTER_LEFT,
      CENTER,
      CENTER_RIGHT,
      BOTTOM_LEFT,
      BOTTOM_CENTER,
      BOTTOM_RIGHT
    };

    enum Units {PIXELS, PERCENT};

    PrecisionPlugin();
    virtual ~PrecisionPlugin();

    bool Initialize(QGLWidget* canvas);
    void Shutdown() {}

    void Draw(double x, double y, double scale);
    void Transform();

    void LoadConfig(const YAML::Node& node, const std::string& path);
    void SaveConfig(YAML::Emitter& emitter, const std::string& path);

    QWidget* GetConfigWidget(QWidget* parent);

  protected:
    void PrintError(const std::string& message);
    void PrintInfo(const std::string& message);
    void PrintWarning(const std::string& message);

  protected Q_SLOTS:
    void SelectFile();
    void FileEdited();

    void SelectTopic();
    void TopicEdited();

    void SetOffsetX(int offset);
    void SetOffsetY(int offset);
    void SetWidth(double width);
    void SetHeight(double height);
    void SetAnchor(QString anchor);
    void SetUnits(QString units);
    void KeepRatioChanged(bool checked);

  private:
    Ui::precision_config ui_;
    QWidget* config_widget_;

    Anchor anchor_;
    Units units_;
    double width_; //image width, if robot frame is x-forward this corresponds to robot length
    double height_; //image height, corresponds to robot width
    double offset_x_; //offset of image center from robot frame along x axis
    double offset_y_; //offset of image center from robot frame along y axis
    double image_ratio_;

    std::string topic_;
    std::string shapefile_;
    std::string imagefile_;

    QImage image_;
    int dimension_;
    int texture_id_;
    bool texture_loaded_;

    bool has_image_;
    bool has_message_;

    double last_width_;
    double last_height_;
    double original_aspect_ratio_;

    ros::NodeHandle nh_;
    ros::Subscriber navsat_sub_;

    cv_bridge::CvImagePtr cv_image_;
    cv::Mat scaled_image_;

    void NavSatFixCallback(const sensor_msgs::NavSatFixConstPtr navsat);

    void LoadImage(const std::string& filename);
    void ScaleImage(double width, double height);
    void DrawIplImage(cv::Mat *image);

    std::string AnchorToString(Anchor anchor);
    std::string UnitsToString(Units units);
  };
}

#endif
